# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PokedexMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
import requests
from pokeapi import pokeinfo


class Ui_PokedexScreen(object):
    def setupUi(self, PokedexScreen):
        PokedexScreen.setObjectName("PokedexScreen")
        PokedexScreen.resize(612, 397)
        PokedexScreen.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        PokedexScreen.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        PokedexScreen.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(PokedexScreen)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("""
        QFrame{\n
        background-color: rgb(225, 134, 134);\n
        border-radius: 25px\n}""")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")

        self.statsFrame = QtWidgets.QFrame(self.dropShadowFrame)
        self.statsFrame.setGeometry(QtCore.QRect(360, 60, 213, 306))
        self.statsFrame.setStyleSheet("""
        QFrame{\n
        background-color: rgb(255, 255, 255);\n
        border-radius: 25px\n}""")
        self.statsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statsFrame.setObjectName("statsFrame")

        self.hp = QtWidgets.QLabel(self.statsFrame)
        self.hp.setGeometry(QtCore.QRect(20, 20, 20, 15))
        self.hp.setStyleSheet("""
        QLabel{\n
        color: rgb(0, 0, 0);\n}""")
        self.hp.setObjectName("hp")

        self.attack = QtWidgets.QLabel(self.statsFrame)
        self.attack.setGeometry(QtCore.QRect(20, 60, 48, 15))
        self.attack.setStyleSheet("""
        QLabel{\n
        color: rgb(0, 0, 0);\n}""")
        self.attack.setObjectName("attack")

        self.defense = QtWidgets.QLabel(self.statsFrame)
        self.defense.setGeometry(QtCore.QRect(20, 110, 59, 15))
        self.defense.setStyleSheet("""
        QLabel{\n
        color: rgb(0, 0, 0);\n}""")
        self.defense.setObjectName("defense")

        self.specialAttack = QtWidgets.QLabel(self.statsFrame)
        self.specialAttack.setGeometry(QtCore.QRect(20, 160, 111, 16))
        self.specialAttack.setStyleSheet("""
        QLabel{\n
        color: rgb(0, 0, 0);\n}""")
        self.specialAttack.setObjectName("specialAttack")

        self.specialDefense = QtWidgets.QLabel(self.statsFrame)
        self.specialDefense.setGeometry(QtCore.QRect(20, 210, 121, 16))
        self.specialDefense.setStyleSheet("""
        QLabel{\n
        color: rgb(0, 0, 0);\n}""")
        self.specialDefense.setObjectName("specialDefense")

        self.speed = QtWidgets.QLabel(self.statsFrame)
        self.speed.setGeometry(QtCore.QRect(20, 260, 41, 16))
        self.speed.setStyleSheet("""
        QLabel{\n
        color: rgb(0, 0, 0);\n}""")
        self.speed.setObjectName("speed")

        self.stat1 = QtWidgets.QLabel(self.statsFrame)
        self.stat1.setGeometry(QtCore.QRect(140, 20, 25, 15))
        self.stat1.setStyleSheet("""
        QLabel{\n
        color: rgb(0, 0, 0);\n}""")
        self.stat1.setText("")
        self.stat1.setObjectName("stat1")

        self.stat2 = QtWidgets.QLabel(self.statsFrame)
        self.stat2.setGeometry(QtCore.QRect(140, 60, 25, 15))
        self.stat2.setStyleSheet("""
        QLabel{\n
        color: rgb(0, 0, 0);\n}""")
        self.stat2.setText("")
        self.stat2.setObjectName("stat2")

        self.stat3 = QtWidgets.QLabel(self.statsFrame)
        self.stat3.setGeometry(QtCore.QRect(140, 110, 25, 15))
        self.stat3.setStyleSheet("""
        QLabel{\n
        color: rgb(0, 0, 0);\n}""")
        self.stat3.setText("")
        self.stat3.setObjectName("stat3")
        
        self.stat4 = QtWidgets.QLabel(self.statsFrame)
        self.stat4.setGeometry(QtCore.QRect(140, 160, 25, 15))
        self.stat4.setStyleSheet("""
        QLabel{\n
        color: rgb(0, 0, 0);\n}""")
        self.stat4.setText("")
        self.stat4.setObjectName("stat4")

        self.stat5 = QtWidgets.QLabel(self.statsFrame)
        self.stat5.setGeometry(QtCore.QRect(140, 210, 25, 15))
        self.stat5.setStyleSheet("""
        QLabel{\n
        color: rgb(0, 0, 0);\n}""")
        self.stat5.setText("")
        self.stat5.setObjectName("stat5")

        self.stat6 = QtWidgets.QLabel(self.statsFrame)
        self.stat6.setGeometry(QtCore.QRect(140, 260, 25, 15))
        self.stat6.setStyleSheet("""
        QLabel{\n
        color: rgb(0, 0, 0);\n}""")
        self.stat6.setText("")
        self.stat6.setObjectName("stat6")

        self.infoFrame = QtWidgets.QFrame(self.dropShadowFrame)
        self.infoFrame.setGeometry(QtCore.QRect(20, 180, 281, 176))
        self.infoFrame.setStyleSheet("""
        QFrame{\n
        background-color: rgb(255, 255, 255);\n
        border-radius: 25px\n}""")
        self.infoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoFrame.setObjectName("infoFrame")

        self.pokemonName = QtWidgets.QLabel(self.infoFrame)
        self.pokemonName.setGeometry(QtCore.QRect(20, 15, 121, 22))
        self.pokemonName.setStyleSheet("""
        QLabel{\n
        color: rgb(0, 0, 0);\n
        font: 18pt;\n}""")
        self.pokemonName.setObjectName("pokemonName")

        self.possibleAbiliities = QtWidgets.QLabel(self.infoFrame)
        self.possibleAbiliities.setGeometry(QtCore.QRect(20, 70, 125, 25))
        self.possibleAbiliities.setStyleSheet("""
        QLabel{\n
        color: rgb(0, 0, 0);\n
        font: 16pt;\n}""")
        self.possibleAbiliities.setObjectName("possibleAbiliities")

        self.abilities = QtWidgets.QLabel(self.infoFrame)
        self.abilities.setGeometry(QtCore.QRect(20, 90, 231, 61))
        self.abilities.setStyleSheet("""
        QLabel{\n
        color: rgb(0, 0, 0);\n
        font: 12pt;\n}""")
        self.abilities.setText("")
        self.abilities.setObjectName("abilities")

        self.type1 = QtWidgets.QLabel(self.infoFrame)
        self.type1.setGeometry(QtCore.QRect(20, 40, 60, 16))
        self.type1.setStyleSheet("""
        QLabel{\n
        border-radius: 2px;\n
        padding: 0 8px;\n
        background: white;\n
        color: white\n}""")

        self.type1.setObjectName("type1")
        self.type2 = QtWidgets.QLabel(self.infoFrame)
        self.type2.setGeometry(QtCore.QRect(80, 40, 60, 16))
        self.type2.setStyleSheet("""
        QLabel{\n
        border-radius: 2px;\n
        padding: 0 8px;\n
        background: white;\n
        color:white\n}""")
        self.type2.setObjectName("type2")

        self.frontSprite = QtWidgets.QLabel(self.dropShadowFrame)
        self.frontSprite.setGeometry(QtCore.QRect(20, 60, 96, 96))
        self.frontSprite.setText(None)
        self.frontSprite.setObjectName("frontSprite")
        self.frontSprite.setStyleSheet("""
        QLabel{\n
        background-color: rgb(255, 255, 255);\n
        border-radius: 25px\n}""")

        self.backSprite = QtWidgets.QLabel(self.dropShadowFrame)
        self.backSprite.setGeometry(QtCore.QRect(200, 60, 96, 96))
        self.backSprite.setText("")
        self.backSprite.setObjectName("backSprite")
        self.backSprite.setStyleSheet("""
        QLabel{\n
        background-color: rgb(255, 255, 255);\n
        border-radius: 25px\n}""")

        self.pokedexLabel = QtWidgets.QLabel(self.dropShadowFrame)
        self.pokedexLabel.setGeometry(QtCore.QRect(20, 10, 191, 45))
        self.pokedexLabel.setStyleSheet("""
        QLabel{\n
        font: 48pt;\n
        color: rgb(255, 251, 0);\n
        border-color: rgb(4, 51, 255);\n
        color: rgb(255, 255, 138);\n}""")
        self.pokedexLabel.setObjectName("pokedexLabel")
        self.pokedexLabel.setText("Pokedex")

        self.searchBar = QtWidgets.QLineEdit(self.dropShadowFrame)
        self.searchBar.setGeometry(QtCore.QRect(360, 20, 211, 24))
        self.searchBar.setStyleSheet("""
        QLineEdit{\n
        color: rgb(0, 0, 0);\n
        border-radius: 10px;\n
        padding: 0 8px;\n
        background: white;\n
        selection-background-color: rgb(255, 255, 162);\n
        selection-color: rgb(0, 0, 0);\n}""")
        self.searchBar.setObjectName("searchBar")
        self.searchBar.setPlaceholderText("Search Pokemon by name or id")

        self.verticalLayout.addWidget(self.dropShadowFrame)
        PokedexScreen.setCentralWidget(self.centralwidget)
        self.searchBar.returnPressed.connect(self.sendValue)
        QtCore.QMetaObject.connectSlotsByName(PokedexScreen)
        
    def sendValue(self):
        if self.searchBar.text() == '0':
            sys.exit(app)
        else:
            if self.searchBar.text()!='':
                pokemon = pokeinfo(self.searchBar.text())
                if(pokemon != None):
                    self.reloadUi(pokemon)
                    self.searchBar.setText('')

    def reloadUi(self, pokemon):
        self.hp.setText("HP")
        self.stat1.setText(pokemon.stats['hp'])
        self.attack.setText("ATTACK")
        self.stat2.setText(pokemon.stats['attack'])
        self.defense.setText("DEFENSE")
        self.stat3.setText(pokemon.stats['defense'])
        self.specialAttack.setText("SPECIAL ATTACK")
        self.stat4.setText(pokemon.stats['special-attack'])
        self.specialDefense.setText("SPECIAL DEFENSE")
        self.stat5.setText(pokemon.stats['special-defense'])
        self.speed.setText("SPEED")
        self.stat6.setText(pokemon.stats['speed'])
        self.pokemonName.setText(pokemon.name.capitalize())
        if len(pokemon.types) > 1:
            self.type1.setText(pokemon.types[0])
            self.type1.setStyleSheet("""
            QLabel{\n
            color:black\n}""")
            self.type2.setText(pokemon.types[1])
            self.type2.setStyleSheet("""
            QLabel{\n
            color:black\n}""")
        else:
            self.type1.setText(pokemon.types[0])
            self.type1.setStyleSheet("""
            QLabel{\n
            color:black\n}""")
            self.type2.setText('')

        front = QImage()
        front.loadFromData(requests.get(pokemon.images['front_default']).content)
        pixmap = QPixmap(front)
        self.frontSprite.setPixmap(pixmap)
        self.frontSprite.resize(pixmap.width(),pixmap.height())

        back = QImage()
        back.loadFromData(requests.get(pokemon.images['back_default']).content)
        pixmap = QPixmap(back)
        self.backSprite.setPixmap(pixmap)
        self.backSprite.resize(pixmap.width(),pixmap.height())
        
        self.possibleAbiliities.setText('Possible Abilities')
        ability = ''
        for x in pokemon.abilities:
            ability += x + '\n'
        self.abilities.setText(ability)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PokedexScreen = QtWidgets.QMainWindow()
    ui = Ui_PokedexScreen()
    ui.setupUi(PokedexScreen)
    PokedexScreen.show()
    sys.exit(app.exec_())
